### ISSUE TITLE
[Bug]  Window decoration breaks on GNOME

### ISSUE THREAD

**Issue by LachCrafter** [not-coded/WayFix#1]
System details:
GNOME 46 (Wayland)
OS - NixOS

Minecraft version: 1.21.1

Issue: When I use the mod, It breaks the GNOME window decoration.
See screenshot.

![image](https://github.com/user-attachments/assets/22629e92-b89c-4845-a703-3fcce4e62fea)

**Comment by not-coded** [comment]
Seems to be related to https://github.com/glfw/glfw/issues/1489
