### ISSUE TITLE
GNOME 47 wayland no app icon for minecraft instance

### ISSUE THREAD

**Issue by 64-bitman** [not-coded/WayFix#3]
Using prism launcher and running minecraft results in the game not having an app icon.

A hacky fix I found was copying the desktop file that WayFix seems to make every time and making it read-only so it can't be deleted. Then replacing the contents with this:
```desktop
[Desktop Entry]
Name=Minecraft 1.21.1
Comment=Explore your own unique world, survive the night, and create anything you can imagine!
Icon=minecraft
NoDisplay=true
Terminal=false
Type=Application
```
I think this is because `Exec=true` exits immediately, so the icon doesn't show in the first place?

**Comment by not-coded** [comment]
> I think this is because `Exec=true` exits immediately, so the icon doesn't show in the first place?

From my own testing it seems the `Hidden=true` is the reason why the icon doesn't show. Removing that seems to fix it.

Use https://github.com/not-coded/WayFix/actions/runs/11446580926

**Comment by 64-bitman** [comment]
This fixes it for me, thank you
